#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generator for the Claude Skills library.

Single source of truth: every SKILL.md under skills/ is generated from the
PROFILES list below. Edit a profile here and re-run this script rather than
hand-editing the generated Markdown, so the whole library stays consistent.
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SKILLS_DIR = os.path.join(ROOT, "skills")


def section(title, items):
    if not items:
        return ""
    body = "\n".join(f"- {it}" for it in items)
    return f"## {title}\n\n{body}\n\n"


def render_skill(p):
    fm_desc = p["description"].replace('"', "'")
    out = []
    out.append("---\n")
    out.append(f"name: {p['name']}\n")
    out.append(f"description: {fm_desc}\n")
    out.append("---\n\n")
    out.append(f"# {p['title']}\n\n")
    out.append(f"{p['mission']}\n\n")
    out.append(section("When to trigger this skill", p["triggers"]))
    out.append(section("Skills, responsibilities and best practices", p["competencies"]))
    out.append(section("Common pitfalls to avoid", p["pitfalls"]))
    out.append(section("Reference stack and tools", p["stack"]))
    out.append(section("Typical deliverables", p["deliverables"]))
    out.append(section("Example prompts that should trigger this skill", p["example_prompts"]))
    if p.get("checklist"):
        out.append("## Quick checklist before delivering\n\n")
        out.append("\n".join(f"- [ ] {c}" for c in p["checklist"]))
        out.append("\n\n")
    if p.get("notes"):
        out.append(f"## Notes\n\n{p['notes']}\n")
    return "".join(out)


PROFILES = []


def add(key, category, name, title, description, mission, triggers, competencies,
        pitfalls, stack, deliverables, example_prompts, checklist=None, notes=None):
    PROFILES.append(dict(key=key, category=category, name=name, title=title, description=description,
                          mission=mission, triggers=triggers, competencies=competencies,
                          pitfalls=pitfalls, stack=stack,
                          deliverables=deliverables, example_prompts=example_prompts,
                          checklist=checklist, notes=notes))

# =========================================================================
# 1. DEV / ENGINEERING
# =========================================================================

add("backend-developer", "dev", "backend-developer", "Backend Developer",
    "Skills and best practices of a senior backend developer for multi-role SaaS platforms: REST/GraphQL APIs, relational data models, role-based auth, payment webhooks, query optimization. Trigger this skill even if the user doesn't say 'backend' explicitly but talks about server-side business logic, database design, or APIs.",
    "The Backend Developer designs, secures and evolves the server-side logic, APIs and data model of the platform. They guarantee transactional consistency (e.g. order status transitions), performance under load, and a clean separation of responsibilities between modules/services.",
    ["Designing or changing an API endpoint (REST/GraphQL)",
     "Modeling or migrating a relational database schema",
     "Role/permission management (e.g. admin, manager, staff, customer)",
     "Integrating webhooks (payment, SMS, notifications)",
     "Optimizing slow queries or database load",
     "Setting up asynchronous processing (queues, background jobs)"],
    ["Modular architecture organized by business domain (orders, users, billing, tenants...)",
     "Normalized relational schemas with indexes matched to real query patterns",
     "Authentication + RBAC (Role-Based Access Control) per business role",
     "Explicit state machines for entities with meaningful status transitions (orders, payments, subscriptions)",
     "Strict input validation (DTOs/schemas) at every API boundary",
     "Idempotent webhook handling to avoid double-processing external events",
     "Unit and integration tests on critical business logic (payments, permissions, money)",
     "Structured logs and traceability for sensitive actions (status changes, refunds, role changes)"],
    ["Mixing business logic into controllers instead of dedicated services",
     "Forgetting pagination on listing endpoints (orders, transactions, users)",
     "Storing monetary amounts as floats instead of integer minor units or a decimal type",
     "Not handling idempotency on payment or other external webhooks",
     "Leaking one tenant's data to another in a multi-tenant system (data isolation failure)",
     "Skipping database transactions on multi-step operations (payment + stock update)"],
    ["Backend framework of your choice (e.g. NestJS, Express, Django, Rails, Laravel, Spring Boot)",
     "Relational database (PostgreSQL, MySQL...) with an ORM/query builder (Prisma, TypeORM, SQLAlchemy...)",
     "Cache and queues (Redis + a job library such as BullMQ, Sidekiq, Celery)",
     "Schema/DTO validation library appropriate to your language",
     "OpenAPI/Swagger for API documentation"],
    ["Documented database schema (ERD)",
     "Documented API endpoints (OpenAPI/Swagger)",
     "Tested modules/services (unit + integration)",
     "Documented roles and permissions"],
    ["'Add an endpoint so an agent can mark a support ticket as resolved'",
     "'How should I structure the orders table with its status lifecycle?'",
     "'Our payment webhook is creating duplicate transactions, help me fix it'",
     "'Design the module that manages regional pricing tiers'"],
    checklist=["Roles and permissions are checked on every sensitive endpoint",
               "Monetary amounts use a precise type (decimal or integer minor units)",
               "Webhooks are idempotent (unique deduplication key)",
               "Database migrations are reversible",
               "Errors return consistent HTTP codes and actionable messages for the frontend"])

add("frontend-developer", "dev", "frontend-developer", "Frontend Developer",
    "Skills and best practices of a frontend developer (React/Vue/similar + TypeScript) for multi-role interfaces and customer-facing storefronts. Trigger this skill for any functional UI task — components, state management, forms, dashboards, responsive/mobile-first, API consumption. Trigger as soon as it's about *functional* UI (not pure visual — see the designer skill for that).",
    "The Frontend Developer turns functional requirements and mockups into performant, accessible, mobile-first interfaces for varied users (admins, staff, field workers, customers), often on unreliable connections.",
    ["Building or changing a UI component",
     "Building a dashboard (admin, staff, operational)",
     "Building a checkout flow or a customer-facing storefront",
     "Complex state management (cart, real-time status, filters)",
     "Frontend performance work (Core Web Vitals, bundle size)",
     "Responsive and mobile-first work for field/low-bandwidth users"],
    ["Component architecture that is typed and reusable (TypeScript)",
     "Server state via a data-fetching library (React Query/TanStack Query, SWR...), local UI state kept separate",
     "Robust forms with schema validation (e.g. React Hook Form + Zod, or the equivalent in your framework)",
     "Mobile-first design when a meaningful share of users are on mobile or low-end devices",
     "Explicit loading/error/empty states, with retry and offline-friendly behavior on unreliable connections",
     "Baseline accessibility (contrast, tap target size, keyboard navigation)",
     "Image optimization and lazy loading for low-bandwidth users",
     "Design system consistency across roles and (if applicable) multiple tenants/brands"],
    ["Duplicating data-fetching logic in every component instead of sharing it",
     "Ignoring slow/unstable connections that are common for field users or emerging markets",
     "Oversized components mixing presentation and business logic",
     "Forgetting network error handling (payment, status updates)",
     "Never testing on small, low-end screens actually used by your target audience",
     "Pulling in heavy libraries that hurt mobile load time for no real benefit"],
    ["Frontend framework of your choice (React, Vue, Svelte...) + TypeScript",
     "Data-fetching layer (TanStack Query, SWR, or your framework's equivalent)",
     "Form + schema validation (React Hook Form + Zod, VeeValidate, etc.)",
     "Accessible component primitives (Radix UI, shadcn/ui, Headless UI...)",
     "Image optimization tooling built into your framework (e.g. next/image or equivalent)"],
    ["Typed, tested UI components",
     "Working dashboards per role",
     "Responsive customer-facing pages",
     "Performance report (Lighthouse/Core Web Vitals)"],
    ["'Build the agent dashboard with today's list of assigned tasks'",
     "'The order form needs to work well on small screens, improve it'",
     "'The storefront loads slowly on mobile, optimize it'",
     "'Add a status filter to the admin order list'"],
    checklist=["Interface tested on a real mobile device or a low-end emulator",
               "Loading/error/empty states explicitly handled",
               "No sensitive data exposed client-side (API keys, tokens)",
               "Components strictly typed, no unjustified `any`"])

add("mobile-developer", "dev", "mobile-developer", "Mobile Developer",
    "Skills of a mobile developer (React Native/Flutter or native) for field applications — sales reps, technicians, inspectors, agents on the move. Trigger this skill for any dedicated mobile app (not a browser), GPS/geolocation, push notifications, offline mode, or app store publishing.",
    "The Mobile Developer builds robust apps for field users who often operate on intermittent connectivity, requiring reliable offline mode and resilient sync.",
    ["Building a mobile app for field workers (technicians, inspectors, agents)",
     "Integrating geolocation/GPS and route tracking",
     "Offline mode and deferred synchronization",
     "Push notifications (new task, status change)",
     "Preparing a release for the Play Store / App Store"],
    ["Justified technical choice between React Native, Flutter and native, based on real constraints",
     "Resilient local storage (SQLite/WatermelonDB or platform equivalent) for offline-first behavior",
     "Sync queue with conflict resolution (e.g. two updates to the same record made offline)",
     "Battery-conscious continuous GPS tracking",
     "Careful permission handling (location, camera for photo evidence/signatures, notifications)",
     "Asset compression to keep app size manageable on limited networks/storage"],
    ["Assuming a permanent network connection when field usage is often intermittent",
     "Tracking GPS continuously without tuning frequency (drains the user's battery)",
     "Ignoring sync conflicts (two offline updates to the same status)",
     "Neglecting app size on the low-end devices actually common in your market",
     "No robust offline mechanism for proof-of-completion (photo, signature)"],
    ["React Native or Flutter",
     "SQLite/WatermelonDB or platform equivalent for offline-first storage",
     "Push notification service (FCM, APNs)",
     "Your existing backend API as the source of truth"],
    ["Working field app for mobile agents",
     "Documented offline sync strategy",
     "Build ready for Play Store / App Store submission"],
    ["'Add offline mode to the field app for low-coverage areas'",
     "'How should I handle photo evidence capture when there's no connection?'",
     "'Optimize battery usage for continuous GPS tracking'"])

add("data-engineer", "dev", "data-engineer", "Data Engineer",
    "Skills of a data engineer for building reliable pipelines (ETL/ELT) between the operational database, an analytical warehouse and reporting tools. Trigger this skill for ingestion, transformation, data quality or pipeline architecture tasks — distinct from the Data Analyst, who works on data that's already ready to query.",
    "The Data Engineer builds and hardens data flows between operational systems (orders, transactions, users) and analytics tooling, guaranteeing quality, freshness and traceability.",
    ["Setting up an ETL/ELT pipeline (operational DB -> warehouse)",
     "Cleaning or deduplicating data at scale",
     "Designing a star schema for reporting",
     "Data quality or freshness problems",
     "Orchestrating scheduled jobs (daily aggregates, exports)"],
    ["Idempotent, replayable pipelines",
     "Dimensional modeling (facts/dimensions) for reporting",
     "Data quality tests (nulls, duplicates, referential integrity)",
     "Orchestration via scheduled jobs or a dedicated tool (Airflow, Dagster) once volume justifies it",
     "Schema evolution handled without breaking existing pipelines",
     "Documented metric definitions (e.g. what exactly counts as a 'completed order'?)"],
    ["Building a pipeline with no data quality tests, propagating bad data downstream",
     "Not handling retries after failure (non-idempotent pipeline)",
     "Over-engineering with heavy tooling before the data volume justifies it",
     "Multiple teams defining the same metric differently (numbers stop matching)"],
    ["Your operational database as the source, materialized views for aggregates",
     "A lightweight BI/warehouse tool matched to your actual volume (Metabase, dbt, or a full warehouse if justified)",
     "Scheduled jobs or an orchestrator for pipeline execution"],
    ["Documented and tested pipelines",
     "Warehouse schema (facts/dimensions)",
     "Metrics dictionary"],
    ["'Build a pipeline that aggregates daily transactions by region every night'",
     "'The dashboard numbers don't match the database, help me investigate'"])

add("ml-ai-engineer", "dev", "ml-ai-engineer", "ML / AI Engineer",
    "Skills of an ML/AI engineer for predictive use cases (risk scoring, completion-time/ETA estimation, fraud detection) applied to a real product. Trigger this skill for any predictive model, scoring, recommendation or anomaly detection request — not for simple descriptive reporting (see Data Analyst).",
    "The ML/AI Engineer designs pragmatic predictive models (risk scoring, ETA estimation, fraud detection) prioritizing simplicity and explainability over unnecessary complexity.",
    ["Risk scoring (e.g. churn risk, payment default risk) by customer/segment",
     "Completion-time or ETA estimation for a task/process",
     "Anomaly or fraud detection (payment, fake accounts)",
     "Recommendation systems for a marketplace or storefront"],
    ["Start with simple baselines (business rules, logistic regression) before deep learning",
     "Feature engineering grounded in real historical outcomes",
     "Time-aware cross-validation (no leakage from future data)",
     "Monitoring for model/data drift in production",
     "Explainability of scores for operational teams who act on them"],
    ["Over-engineering with complex models on insufficient data",
     "Training on biased data (e.g. only successful transactions)",
     "Deploying a model with no monitoring or retraining plan",
     "Ignoring explainability when decisions affect real users"],
    ["Python (scikit-learn, pandas) for prototyping",
     "Your operational database as the feature source",
     "A backend endpoint to serve the score/prediction in production"],
    ["Documented predictive model with performance metrics",
     "Reproducible feature pipeline",
     "Model monitoring plan"],
    ["'Can you design a risk score for orders with a high failure/cancellation rate?'",
     "'How should I estimate task completion time based on segment and history?'"])

add("qa-test-engineer", "dev", "qa-test-engineer", "QA / Test Engineer",
    "Skills of a QA engineer for guaranteeing platform reliability through test strategy (unit, integration, end-to-end) and regression detection. Trigger this skill for test plans, writing automated tests, functional acceptance testing, or bug triage.",
    "The QA/Test Engineer defines the test strategy and makes sure no critical feature (payments, permissions, status transitions) regresses silently.",
    ["Writing a test plan for a new feature",
     "Writing automated tests (unit, integration, E2E)",
     "Functional acceptance testing before a release",
     "Analyzing and reproducing a reported bug"],
    ["Balanced test pyramid (many unit tests, some integration, few E2E)",
     "E2E coverage on critical journeys (browse -> checkout -> payment -> fulfillment)",
     "Systematic regression testing before each deployment",
     "Realistic, isolated test data (never polluting production)",
     "Reproducible bug reports (steps, environment, expected vs actual result)"],
    ["Testing only the happy path, ignoring error cases (payment declined, out of stock)",
     "Flaky tests that depend on execution order or shared, non-isolated data",
     "No tests on role-based permissions (a standard user shouldn't reach the admin panel)",
     "Validating in a test environment that differs meaningfully from production"],
    ["Jest/Vitest (or your language's unit test framework)",
     "Playwright or Cypress for E2E",
     "Supertest or equivalent for API testing"],
    ["Documented test plan",
     "Automated test suite",
     "Structured bug report"],
    ["'Write the tests for the payment flow, including failure cases'",
     "'Prepare the acceptance checklist for the new operator interface before release'"])

add("database-administrator", "dev", "database-administrator", "Database Administrator (DBA)",
    "Skills of a PostgreSQL DBA for performance, backup, security and scalability of the platform's database. Trigger this skill for query performance, indexing, backup/restore, replication or database capacity planning questions.",
    "The DBA keeps the database performant, available and secure as the volume of transactions, users and tenants grows.",
    ["Slow queries or execution plans to analyze (EXPLAIN ANALYZE)",
     "Backup/restore strategy and disaster recovery plan",
     "Sizing and indexing for data growth",
     "Replication or high availability",
     "Locks/deadlocks in production"],
    ["Systematic execution-plan analysis before adding an index",
     "Composite indexes aligned with real query patterns (status + date filters, per-tenant filters)",
     "Automated backups that are regularly tested via an actual restore",
     "Partitioning large tables (transactions, logs) once volume justifies it",
     "Query-level tenant isolation in multi-tenant systems (avoid cross-tenant full scans)",
     "Monitoring active connections and pool usage (PgBouncer or equivalent if needed)"],
    ["Adding indexes without measuring real impact on frequent queries",
     "Backups that are never tested via restore (false sense of security)",
     "Letting log tables grow unbounded with no retention/archival policy",
     "No connection pooling under load (connection exhaustion)"],
    ["PostgreSQL (or your relational database of choice)",
     "Connection pooler (PgBouncer or equivalent)",
     "Backup tooling (pg_dump/pg_basebackup or a managed solution)",
     "Monitoring extensions (pg_stat_statements or equivalent)"],
    ["Performance analysis report",
     "Documented and tested backup/restore plan",
     "Justified indexing strategy"],
    ["'The order list takes 5 seconds to load in admin, help me diagnose it'",
     "'Set up a reliable backup strategy for the production database'"])

add("devops", "dev", "devops-engineer", "DevOps Engineer",
    "DevOps skills for continuous integration/deployment, containerization and infrastructure of the SaaS platform. Trigger this skill for CI/CD, Docker, orchestration, environment management (dev/staging/prod), or server/cloud configuration.",
    "The DevOps Engineer automates software delivery (CI/CD), hardens environments, and prepares infrastructure to scale in a cost-controlled way.",
    ["Setting up or improving a CI/CD pipeline",
     "Containerizing services (Docker)",
     "Managing dev/staging/production environments",
     "Configuring servers, reverse proxy, SSL certificates",
     "Secrets and environment variable management"],
    ["CI/CD pipelines with clear stages: lint -> test -> build -> deploy",
     "Lightweight, reproducible Docker images (multi-stage builds)",
     "Strict environment separation via configuration/environment variables",
     "Zero-downtime deploys (rolling/blue-green where it matters)",
     "Centralized, encrypted secrets management (never hardcoded in the repo)",
     "Baseline monitoring (uptime, centralized logs) from the first deployment"],
    ["Manual, non-reproducible production deploys",
     "Secrets committed to git or checked into versioned config files",
     "No staging environment representative of production",
     "Over-provisioning infrastructure before real load justifies the cost"],
    ["Docker / Docker Compose",
     "GitHub Actions (or your CI provider) for CI/CD",
     "Nginx or Traefik as reverse proxy",
     "A cloud/VPS provider sized to your stage",
     "Coolify/Dokploy or similar as a simplified deployment option for small teams"],
    ["Working CI/CD pipeline",
     "Optimized Dockerfiles",
     "Documented environments and variables"],
    ["'Set up a CI/CD pipeline that deploys automatically to staging'",
     "'Containerize the backend and frontend cleanly'"])

add("sre", "dev", "site-reliability-engineer", "SRE (Site Reliability Engineer)",
    "SRE skills for reliability, monitoring, SLAs and incident management in production. Trigger this skill for availability questions, alerting, incident post-mortems, or defining reliability objectives (SLO/SLA) — complementary to DevOps, which focuses on deployment.",
    "The SRE defines and protects the reliability users actually experience through clear service objectives, proactive monitoring and structured incident management.",
    ["Defining SLOs/SLAs (e.g. availability of a critical API)",
     "Setting up alerting and system health dashboards",
     "Managing and running a post-mortem for a production incident",
     "Capacity planning ahead of a predictable high-load period"],
    ["SLOs defined around real user experience, not just raw technical metrics",
     "Actionable alerting (every alert should map to a possible action)",
     "Blameless post-mortems focused on systemic causes",
     "Documented runbooks for recurring incidents",
     "Load testing ahead of predictable peaks (seasonal spikes, campaigns)"],
    ["Piling on non-actionable alerts (alert fatigue, real incidents get ignored)",
     "No post-mortem after an incident -> the same failure repeats",
     "Not anticipating predictable load spikes"],
    ["Uptime monitoring (e.g. UptimeRobot, Better Stack)",
     "Centralized logs",
     "Application and infrastructure metric dashboards"],
    ["Documented SLOs/SLAs",
     "Incident runbooks",
     "Post-mortem report"],
    ["'Define availability objectives for the order-tracking API'",
     "'Run the post-mortem for last night's payment outage'"])

add("solutions-architect", "dev", "solutions-architect", "Solutions / Software Architect",
    "Skills of a software architect for structural decisions: module/service boundaries, technology choices, technical debt management, multi-tenant scalability. Trigger this skill for high-level architecture decisions, not day-to-day implementation (see backend/frontend developer for that).",
    "The Solutions Architect keeps the platform technically coherent end to end, anticipates scalability, and arbitrates technical trade-offs with a long-term view.",
    ["Deciding on modular boundaries or a move toward microservices",
     "A structural technology choice (new datastore, new language, new third-party service)",
     "Designing multi-tenant isolation",
     "Architecture review ahead of a major feature",
     "Managing and prioritizing technical debt"],
    ["Modular monolith before microservices, until complexity actually demands the split",
     "Clear multi-tenant isolation strategy (shared schema + tenant_id vs. separate schemas, based on scale)",
     "Documented architecture decisions (ADRs — Architecture Decision Records)",
     "Anticipating scalability without premature over-engineering",
     "Consistent API contracts across frontend/backend/mobile teams"],
    ["Adopting microservices before there's a real need (unnecessary complexity)",
     "Undocumented architecture decisions (lost context down the line)",
     "Ignoring multi-tenant implications when shipping new features",
     "Choosing technology by hype rather than fit for team, market and cost constraints"],
    ["A modular-monolith-first approach, evolving toward microservices only if needed",
     "ADRs (Architecture Decision Records) for documentation"],
    ["High-level architecture diagram",
     "ADRs (documented architecture decisions)",
     "Prioritized technical roadmap"],
    ["'How should I cleanly isolate each seller's data on a multi-tenant marketplace?'",
     "'Should we move the payment module to microservices?'",
     "'Document the architecture decision for the new fulfillment module'"])

# =========================================================================
# 2. SECURITY
# =========================================================================

add("pentester", "security", "pentester", "Pentester (Penetration Tester)",
    "Skills of a penetration tester for finding exploitable vulnerabilities (API, authentication, multi-tenant isolation) before an attacker does. Trigger this skill for penetration testing, offensive security audits, or vulnerability exploitation within an authorized engagement.",
    "The Pentester simulates real, controlled attacks against the platform to surface exploitable flaws, with an actionable report for engineering teams.",
    ["Offensive security audit before shipping a sensitive feature",
     "Penetration testing on the API or multi-role authentication",
     "Verifying multi-tenant isolation (one tenant must never reach another tenant's data)",
     "Testing payment flows for possible manipulation"],
    ["Structured methodology (OWASP Testing Guide, OWASP API Security Top 10)",
     "Systematic access-control testing (IDOR, privilege escalation)",
     "Verifying tenant isolation (cross-tenant data access attempts)",
     "Testing authentication mechanisms (tokens, session handling, password reset)",
     "Testing for injection (SQL, NoSQL, command) and input validation gaps",
     "Report with proof of concept, severity (CVSS) and concrete remediation guidance"],
    ["Testing in production without authorization or a maintenance window",
     "Relying only on automated scans without manually validating false positives",
     "A vulnerability report with no prioritization or concrete fix guidance",
     "Ignoring business-logic flaws (e.g. manipulating a client-side price or amount)"],
    ["Burp Suite / OWASP ZAP for interception and API testing",
     "OWASP API Security Top 10 as a reference framework",
     "Postman/Insomnia for crafting API requests"],
    ["Pentest report with severity ratings and evidence",
     "Prioritized vulnerability list with remediation guidance",
     "Retest after fixes are applied"],
    ["'Can you identify possible flaws in our role-based authentication?'",
     "'Check whether one tenant can reach another tenant's data on the platform'"],
    notes="Stay strictly within a legal framework: written authorization is mandatory before any real test, and applicable local cybersecurity and data protection regulations must be respected.")

add("soc-analyst", "security", "soc-analyst", "SOC Analyst",
    "Skills of a SOC (Security Operations Center) analyst for continuous monitoring, detection and triage of security incidents. Trigger this skill for setting up security monitoring, analyzing suspicious logs, alert triage, or detecting abnormal activity.",
    "The SOC Analyst continuously watches the platform's security signals (logins, API, payments) to quickly detect and qualify suspicious activity.",
    ["Setting up security monitoring (logs, alerts)",
     "Analyzing reported suspicious activity (abnormal logins, request spikes)",
     "Triaging and qualifying a security alert",
     "Correlating events across multiple systems (auth, payments, API)"],
    ["Centralizing security logs (auth, API, payments) in one place",
     "Detection rules based on abnormal behavior (repeated login attempts, rapid IP changes)",
     "Fast triage: distinguish false positive, minor incident, major incident",
     "Clear escalation path to Blue Team / Incident Responder once an incident is confirmed",
     "Documenting each handled alert to refine future detection rules"],
    ["Configuring overly noisy alerts that drown out real signals",
     "Analyzing logs without cross-system correlation (auth, payments, API) -> fragmented picture",
     "No clear escalation procedure once an incident is confirmed"],
    ["Centralized logging (e.g. Grafana Loki, or a lighter solution matched to budget)",
     "Detection rules on login attempts and API anomalies",
     "Security dashboards"],
    ["Documented detection rules",
     "Alert triage report",
     "Security monitoring dashboard"],
    ["'Set up monitoring for suspicious login attempts on the admin panel'",
     "'Is there an abnormal spike in API requests overnight — can you analyze the logs?'"])

add("blue-team", "security", "blue-team", "Blue Team (Defense)",
    "Blue Team skills for defense, hardening and structured incident response. Trigger this skill for configuration hardening, defensive strategy, or improving the overall security posture — broader than the SOC's day-to-day monitoring focus.",
    "The Blue Team continuously strengthens the platform's defensive posture: configuration hardening, patch management, and improving detection and response capability.",
    ["Hardening a server, database or API",
     "Defining an overall defensive strategy",
     "Responding to an active security incident",
     "Reviewing security configuration (HTTP headers, CORS, secrets)"],
    ["Least-privilege access everywhere (database, API, servers)",
     "HTTP header hardening (CSP, HSTS, restrictive CORS)",
     "Rigorous secrets management with regular key rotation",
     "Documented, tested incident response plan (who does what, in what order)",
     "Regular dependency updates (audit tooling) to limit known-vulnerability exposure"],
    ["Neglecting dependency updates (known vulnerabilities stay exploitable)",
     "Overly permissive CORS configuration (`*`) exposing the API to unwanted origins",
     "No tested incident response plan before a real incident happens"],
    ["HTTP security header middleware (e.g. Helmet.js or your framework's equivalent)",
     "Dependency auditing (npm audit / Snyk or equivalent)",
     "Strict CORS policy",
     "Secrets management (Vault, or encrypted environment variables)"],
    ["Applied hardening checklist",
     "Incident response plan",
     "Dependency audit report"],
    ["'How do we harden our API configuration against common attacks?'",
     "'Prepare a response plan for a customer data leak scenario'"])

add("red-team", "security", "red-team", "Red Team",
    "Red Team skills for simulating full, realistic attacks (beyond a simple technical pentest) including social engineering and persistence, to test the organization's overall resilience. Trigger this skill for advanced, multi-vector attack simulation exercises within a strictly authorized scope.",
    "The Red Team simulates a realistic, determined adversary to assess overall resilience — technical, human and organizational — of the platform and the team.",
    ["A full, authorized attack simulation exercise (technical + human)",
     "Testing resilience against a multi-vector attack (phishing + technical exploitation)",
     "Evaluating the defending team's (Blue Team) detection and response"],
    ["Realistic attack scenarios based on plausible threats for your industry",
     "Clear, measurable objectives (e.g. 'reach a tenant's payment data')",
     "Coordination with leadership on authorization and scope (Rules of Engagement)",
     "A report detailing the full attack path and the detection gaps found",
     "Constructive debrief with the Blue Team after the exercise"],
    ["Running an exercise with no written, leadership-approved Rules of Engagement",
     "Confusing Red Team with a simple, isolated technical pentest",
     "Not sharing lessons with the Blue Team afterward (value lost)"],
    ["Standard pentest tooling + simulated social engineering techniques",
     "Frameworks such as MITRE ATT&CK to structure scenarios"],
    ["Documented Rules of Engagement",
     "Full attack scenario report",
     "Prioritized hardening recommendations"],
    ["'Prepare a full attack simulation scenario including targeted phishing against our team'"],
    notes="A sensitive exercise: requires explicit written authorization from leadership and a strict legal framework before any execution, especially for any social-engineering component.")

add("purple-team", "security", "purple-team", "Purple Team",
    "Purple Team skills for bridging offense (Red Team) and defense (Blue Team), turning every offensive test into a measurable defensive improvement. Trigger this skill to coordinate a joint red/blue exercise, improve detection rules after a pentest, or measure defensive coverage.",
    "The Purple Team makes sure every vulnerability found by a simulated attack turns into a concrete improvement in defenses and detection capability.",
    ["Coordinating a joint Red Team / Blue Team exercise",
     "Translating pentest findings into concrete detection rules",
     "Measuring defensive coverage against known attack techniques"],
    ["Joint workshops where the attacker explains their technique live to the defender",
     "Mapping tested techniques against detected techniques (coverage matrix)",
     "Prioritizing defensive improvements by real demonstrated impact",
     "A continuous feedback loop rather than a one-off exercise"],
    ["Treating Red Team and Blue Team as siloed groups with no shared learning",
     "Measuring only the number of vulnerabilities found, not whether fixes actually landed"],
    ["MITRE ATT&CK matrix as a shared reference framework",
     "Issue tracking linked to each finding's remediation"],
    ["Attack/detection coverage matrix",
     "Prioritized defensive improvement plan"],
    ["'After the last pentest, help me turn the findings into concrete detection rules'"])

add("ciso-grc", "security", "ciso-grc", "CISO / GRC (Governance, Risk, Compliance)",
    "Skills of a CISO/GRC lead for security governance, risk management and regulatory compliance (personal data, payments). Trigger this skill for security policy, risk analysis, data-protection compliance in your jurisdiction, or organization-level security management.",
    "The CISO/GRC lead drives the company's overall security strategy — risk management, regulatory compliance, security policy and team awareness — with a business lens, not just a technical one.",
    ["Defining an information security policy",
     "Risk analysis (new vendors, new sensitive features)",
     "Coming into compliance with the applicable data protection regulation in your target market",
     "Preparing for a security audit or certification",
     "Running a security awareness program for the team"],
    ["Structured risk analysis (likelihood x impact) for every sensitive decision",
     "A security policy that's written, accessible and actually applied — not a dead document",
     "A personal-data processing register compliant with your local legal requirements",
     "An incident response plan that covers legal breach-notification obligations",
     "Regular team security awareness (phishing, password hygiene, customer data handling)"],
    ["A purely formal security policy that's never applied in practice",
     "Ignoring the specific legal obligations around personal data in your target market",
     "Treating compliance as a blocker instead of a trust framework for customers"],
    ["A reference framework such as ISO 27001, scaled to your company's actual size",
     "A risk register and a data-processing register"],
    ["Documented security policy",
     "Risk register",
     "Personal data processing register"],
    ["'Help me draft a data security policy for our customers'",
     "'What are our legal obligations around personal data in our target market for this SaaS?'"],
    notes="Always verify the applicable laws and regulator for your specific jurisdiction before relying on any compliance guidance produced here — this is a starting point, not final legal advice.")

add("incident-responder", "security", "incident-responder-forensics", "Incident Responder / Forensics",
    "Skills of an incident responder and forensic investigator for containing, analyzing and documenting a security incident that has already happened. Trigger this skill as soon as a real security incident is in progress or confirmed (data leak, account compromise, unauthorized access) — distinct from the SOC's preventive monitoring.",
    "The Incident Responder quickly contains a confirmed security incident, preserves evidence, determines root cause, and documents the incident to prevent recurrence.",
    ["A confirmed security incident (account compromise, unauthorized access, data leak)",
     "Forensic analysis following confirmed suspicious activity",
     "Writing an incident report for leadership or relevant authorities",
     "Determining the root cause of a compromise"],
    ["Structured methodology: identification -> containment -> eradication -> recovery -> lessons learned",
     "Preserving evidence before any remediation action (logs, snapshots)",
     "Controlled, factual communication during the incident (avoid panic or over-communication)",
     "A precise timeline of events for the final report",
     "Notifying affected parties if personal data is involved"],
    ["Fixing immediately without preserving evidence (root cause becomes unknowable)",
     "Rushing public communication before the facts are confirmed",
     "No formal post-incident report -> no organizational learning"],
    ["Centralized logs and database snapshots",
     "Log analysis and event-timeline tooling"],
    ["Full incident report (timeline, root cause, actions taken)",
     "Remediation plan",
     "Communication to affected parties if required"],
    ["'An admin account looks compromised, help me contain and investigate it'",
     "'Write the post-incident report for yesterday's data leak'"])

# =========================================================================
# 3. DESIGN / PRODUCT
# =========================================================================

add("ui-ux-designer", "design-product", "ui-ux-designer", "UI/UX Designer",
    "Skills of a UI/UX designer for modern, premium, mobile-first interfaces (storefronts, SaaS dashboards). Trigger this skill for aesthetics, wireframes, user flows, design systems or the visual identity of an interface.",
    "The UI/UX Designer creates interfaces that are clear, premium and culturally relevant for mobile-first users, balancing modern aesthetics with real-world usability.",
    ["Designing wireframes or high-fidelity mockups",
     "Defining or evolving the design system (colors, typography, components)",
     "Designing a user journey (checkout, account onboarding)",
     "Visual refresh toward a more premium, professional look"],
    ["Systematic mobile-first design when most users are on mobile",
     "A consistent, documented design system (colors, typography, spacing, components)",
     "Clear visual hierarchy for users with varying levels of digital literacy",
     "A premium yet approachable aesthetic, adapted to your actual target audience and culture",
     "Fast prototyping and testing of critical flows (checkout, payment, tracking)",
     "Sufficient contrast and font size for outdoor/bright-light readability if relevant to your users"],
    ["Copying a design system from another market without adapting it to actual users",
     "Interfaces overloaded with text or technical jargon for non-expert users",
     "Neglecting loading/error states in mockups (incomplete experience)",
     "Visual inconsistency across role-based interfaces (admin, staff, customer)"],
    ["Figma for design and prototyping",
     "Reusable design tokens implemented in your CSS framework",
     "A component library shared with frontend (shadcn/ui, Radix, etc.)"],
    ["High-fidelity mockups",
     "Documented design system",
     "Interactive prototype of the key flow"],
    ["'Redesign the homepage so it feels more premium and professional'",
     "'Design the onboarding flow for a new business account'",
     "'Create a consistent design system across all our role-based interfaces'"])

add("product-manager", "design-product", "product-manager", "Product Manager",
    "Skills of a Product Manager for prioritizing the roadmap, writing clear functional specs, and balancing user needs against technical constraints. Trigger this skill for feature prioritization, user stories, or product roadmap definition.",
    "The Product Manager turns business vision into a concrete roadmap, prioritizes by value vs. effort, and makes sure every shipped feature solves a real user problem.",
    ["Prioritizing features for the next sprint/quarter",
     "Writing functional specs or user stories",
     "Arbitrating between competing needs from different user segments",
     "Defining success metrics for a new feature"],
    ["Prioritization based on business value and effort (e.g. RICE or MoSCoW framework)",
     "User stories with clear, testable acceptance criteria",
     "Validating product hypotheses with real usage data before over-investing",
     "Defining measurable success metrics before a feature ships",
     "Communicating the roadmap and the reasoning behind priorities clearly to the team"],
    ["Prioritizing by whoever asks loudest rather than by real value",
     "Vague specs that leave too much open to interpretation during development",
     "Shipping features with no success metric defined up front",
     "Ignoring technical debt in prioritization (everything goes to features)"],
    ["A roadmap/ticket tool (Notion/Linear/Jira)",
     "A prioritization framework (RICE, MoSCoW)",
     "Product analytics to measure real usage (Mixpanel, PostHog)"],
    ["Prioritized roadmap",
     "User stories with acceptance criteria",
     "Defined success metrics per feature"],
    ["'Help me prioritize between improving the admin dashboard and the mobile app'",
     "'Write the user stories for the product return feature'"])

add("ux-researcher", "design-product", "ux-researcher", "UX Researcher",
    "Skills of a UX Researcher for understanding real user needs (business customers, field workers, end customers) through qualitative and quantitative methods. Trigger this skill for user interview guides, usability testing, or behavioral analysis.",
    "The UX Researcher goes to the ground truth with business customers, field workers and end users to inform product decisions with real data instead of assumptions.",
    ["Preparing user interviews (business customers, field workers, end users)",
     "Designing a usability test for a new interface",
     "Analyzing user feedback or support tickets to spot patterns",
     "Validating a product hypothesis before development"],
    ["Interview guides with open questions that avoid confirmation bias",
     "Recruiting users representative of the different roles and digital-literacy levels",
     "Usability tests built around concrete tasks rather than abstract questions",
     "Synthesizing insights into actionable recommendations for product/design",
     "Triangulating qualitative (interviews) and quantitative (analytics) data"],
    ["Asking leading questions that bias user responses",
     "Interviewing only tech-savvy users unrepresentative of the real user base",
     "Gathering insights without turning them into concrete, prioritized recommendations"],
    ["Structured interview guides",
     "Recording/transcription tooling",
     "Behavioral analytics (Hotjar, PostHog) to complement qualitative research"],
    ["Interview guide",
     "User insights synthesis",
     "Usability test report"],
    ["'Prepare an interview guide to understand why field workers abandon the app'",
     "'Design a usability test for the new checkout flow'"])

add("accessibility-specialist", "design-product", "accessibility-specialist", "Accessibility Specialist",
    "Skills of an accessibility (a11y) specialist for making interfaces usable by as many people as possible, including on slow connections, low-end screens or with visual limitations. Trigger this skill for accessibility audits, WCAG compliance, or improving the inclusiveness of an interface.",
    "The Accessibility Specialist makes sure interfaces stay usable across highly varied real-world conditions: small screens, bright outdoor light, slow connections, users unfamiliar with digital products.",
    ["Auditing an existing interface for accessibility",
     "Checking compliance against WCAG standards",
     "Improving readability for outdoor use (field workers in direct sunlight)",
     "Adapting an interface for users unfamiliar with digital products"],
    ["Sufficient contrast for outdoor/bright-light readability where relevant",
     "Tap targets large enough for mobile use while moving or wearing gloves",
     "Simple navigation, clear language, avoiding technical jargon",
     "Basic screen-reader support on critical flows (forms, payment)",
     "Interfaces that degrade gracefully on slow connections rather than breaking"],
    ["Reducing accessibility to WCAG checkbox compliance without thinking about real usage conditions",
     "Text- or option-heavy interfaces that lose users unfamiliar with digital products",
     "Ignoring accessibility for field-facing roles in favor of the back office only"],
    ["WCAG 2.1/2.2 as a reference standard",
     "Audit tooling (axe DevTools, Lighthouse)",
     "Real testing on low-end phones"],
    ["Accessibility audit report",
     "Compliance checklist",
     "Recommendations prioritized by user impact"],
    ["'Check whether the field app stays readable in direct sunlight on a low-end phone'",
     "'Audit the checkout flow's accessibility for users who aren't comfortable with technology'"])

# =========================================================================
# 4. BUSINESS / STRATEGY
# =========================================================================

add("ceo", "business-strategy", "ceo-strategy", "CEO / Executive Leadership",
    "Executive leadership skills for vision, overall strategy, structural decisions and stakeholder communication (investors, partners, key accounts). Trigger this skill for company vision, growth strategy, market positioning, or high-impact business decisions.",
    "The CEO sets the vision, arbitrates priorities across product/tech/business, and carries the company's credibility with investors, partners and institutional customers.",
    ["Defining or clarifying company vision and strategy",
     "A structural decision (product pivot, new market, fundraising)",
     "Preparing communication for investors or strategic partners",
     "Arbitrating between competing priorities (product, tech, sales, security)"],
    ["A vision that's clear and communicable in one sentence to every stakeholder",
     "Decisions grounded in real data (market, traction, unit economics) rather than intuition alone",
     "Anticipating regulatory and market-specific risks in your target geography",
     "Transparent, regular communication with the team about priorities and their rationale",
     "Rigorous tracking of key indicators (growth, retention, margin, cash runway)"],
    ["Stacking too many simultaneous strategic priorities with no real trade-off",
     "Deciding without real market or traction data",
     "Neglecting legal/financial structuring in favor of product growth alone",
     "Inconsistent vision communication between investors, team and customers"],
    ["Business KPI dashboards",
     "A documented business plan and economic model",
     "Investor relationship management tools"],
    ["Documented vision and strategy",
     "Updated business plan",
     "Investor/partner presentation"],
    ["'Help me clarify our value proposition ahead of fundraising'",
     "'How should I prioritize between geographic expansion and improving the current product?'"])

add("cto", "business-strategy", "cto", "CTO",
    "Skills of a CTO for aligning technical strategy with business vision, structuring the engineering team, and arbitrating technology investments. Trigger this skill for technical decisions with high organizational impact — distinct from the Solutions Architect, who focuses on the system architecture itself.",
    "The CTO turns business strategy into technology priorities, structures and grows the engineering team, and makes sure technical choices stay sustainable over time and budget.",
    ["Defining overall technology strategy (build vs. buy, stack, hiring)",
     "Structuring the engineering team (roles, process, methodology)",
     "Balancing shipping speed against quality/technical debt",
     "Technical communication with investors or partners"],
    ["Systematically aligning technical priorities with current business goals",
     "Pragmatic build-vs-buy decisions (don't reinvent what already exists, e.g. payment infrastructure)",
     "Visible, prioritized technical debt management, not ignored until it becomes a crisis",
     "Development process sized to the actual team, not over-engineered for a bigger org",
     "Documenting major technical decisions for organizational continuity"],
    ["Choosing technology for prestige rather than fit for context and team",
     "Letting technical debt pile up without ever making it visible to leadership",
     "Over-processing a small team with methodology built for large organizations"],
    ["Your engineering stack of choice, matched to team skills and market constraints",
     "Technical project management tooling (Linear, Jira, sized to team)"],
    ["Documented technical strategy",
     "Technical roadmap aligned with business goals",
     "Defined team structure and process"],
    ["'Should we build our own risk-scoring solution or use an existing service?'",
     "'Help me structure the engineering team for the next 6 months'"])

add("business-analyst", "business-strategy", "business-analyst", "Business Analyst",
    "Skills of a Business Analyst for translating business needs into clear specifications and evaluating the business impact of product/tech decisions. Trigger this skill for business process analysis, requirements documents, or ROI studies for a feature.",
    "The Business Analyst bridges concrete business needs (operations, sales, support) and the product/tech teams, making sure every build has a measurable business impact.",
    ["Analyzing an existing business process to optimize (order handling, returns management)",
     "Writing a functional requirements document",
     "An ROI study before investing in a feature",
     "Impact analysis of a process change on different teams"],
    ["Precisely mapping the existing process before proposing a change",
     "Requirements docs with explicit business rules (e.g. when exactly is a transaction considered failed?)",
     "A quantified cost/benefit analysis before recommending any investment",
     "Involving operational teams in validating requirements",
     "Traceable documentation from the original business need to the final technical spec"],
    ["Writing specs without validating the real process with the operational teams",
     "Recommending an investment with no quantified expected benefit",
     "Ambiguous requirements that leave room for contradictory interpretation during development"],
    ["Process modeling tools (BPMN where useful, or simple diagrams)",
     "Spreadsheets for cost/benefit analysis"],
    ["Functional requirements document",
     "Business process map",
     "ROI study"],
    ["'Analyze the current returns process and suggest improvements'",
     "'Quantify the ROI of automating follow-ups on pending orders'"])

add("project-manager", "business-strategy", "project-manager", "Project Manager / Scrum Master",
    "Skills of a Project Manager / Scrum Master for organizing team work, managing timelines, and facilitating collaboration between technical and business roles. Trigger this skill for project/sprint planning, or progress tracking.",
    "The Project Manager/Scrum Master structures team work to deliver on time, with smooth communication between the technical, design and business people involved.",
    ["Planning a project or sprint",
     "Tracking progress and managing blockers",
     "Facilitating team rituals (retro, planning)",
     "Managing priorities and deadlines with stakeholders"],
    ["Breaking work into deliverable, estimable units",
     "Proactively identifying dependencies and potential blockers",
     "Regular, transparent progress communication to stakeholders",
     "Team rituals sized to the actual team, not over-processed for a small group",
     "Documenting decisions made in meetings to avoid later misunderstandings"],
    ["Planning with no buffer for the unexpected (bugs, external dependencies)",
     "Piling on meetings with no clear value for a small team",
     "Not tracking blockers until they become critical to the deadline"],
    ["Linear, Notion or Trello for task tracking",
     "An agile methodology matched to context (light Scrum or Kanban)"],
    ["Project/sprint plan",
     "Progress report",
     "Risk and blocker log"],
    ["'Help me plan the sprint to ship v2 within the 4-week window'",
     "'How should design and backend coordinate their work on this project?'"])

add("legal-compliance", "business-strategy", "legal-compliance", "Legal & Compliance",
    "Legal and compliance skills for contractual matters, personal data protection and applicable regulation for a SaaS/payments business. Trigger this skill for contracts, terms of service, personal data compliance, or local regulation questions — Claude provides informational framing here, not final legal advice.",
    "The Legal & Compliance profile structures the platform's contractual and regulatory posture (terms of service, client contracts, data protection) to keep the business on solid legal footing in its target market.",
    ["Drafting or reviewing terms of service/sale",
     "Structuring a client contract (scope, price, deliverables)",
     "Personal data protection compliance",
     "A local regulatory question about payments"],
    ["Contracts with explicit, unambiguous scope, timelines and payment terms",
     "Clear IP clauses on code and deliverables developed for a client",
     "Compliance with the personal data protection rules applicable in your jurisdiction",
     "Anticipating regulatory changes around digital payments",
     "Always recommending validation by a local qualified lawyer for anything contractually binding"],
    ["Treating a verbal or informal agreement as sufficient for significant amounts and stakes",
     "Ignoring IP clauses on code developed for a client",
     "Presenting a generated answer as final legal advice with no professional review"],
    ["SaaS-appropriate contract and terms-of-service templates",
     "Personal data protection reference frameworks"],
    ["Structured contract or terms of service",
     "Compliance note",
     "Personal data processing register"],
    ["'Help me structure the clauses of my client contract'",
     "'What do I need to cover in my terms of service?'"],
    notes="Any output on this topic is informational and must be validated by a qualified lawyer in your jurisdiction before signature or official publication.")

add("growth-sales", "business-strategy", "growth-sales", "Growth / Sales Specialist",
    "Growth and sales skills for structuring customer acquisition and optimizing the sales conversion funnel. Trigger this skill for acquisition strategy, sales pitches, conversion funnels, or pricing.",
    "The Growth/Sales Specialist structures acquisition and conversion of new customers (B2B accounts, business clients) with an approach fit for the realities of the target market.",
    ["Structuring a B2B customer acquisition strategy",
     "Writing a sales pitch or pitch deck",
     "Optimizing a conversion funnel (free trial -> paying customer)",
     "Defining or adjusting a pricing model"],
    ["A clear, differentiated value proposition adapted to the local market context",
     "An acquisition funnel with measurable steps (lead -> demo -> trial -> customer)",
     "Pricing aligned with perceived value and the target market's actual willingness/ability to pay",
     "Sales pitches backed by concrete evidence (use cases, quantified gains)",
     "Tracking acquisition metrics (CAC, conversion rate, churn)"],
    ["Copying a pricing/growth playbook from another market without adapting it to local purchasing power",
     "A sales pitch focused on the technology rather than the concrete business benefit",
     "No tracking of acquisition metrics (flying blind)"],
    ["A lightweight CRM for pipeline tracking",
     "Acquisition analytics tooling"],
    ["Documented acquisition strategy",
     "Sales pitch/deck",
     "Justified pricing model"],
    ["'Help me structure a pitch to convince business accounts to join the platform'",
     "'How should I price our SaaS for our target market?'"])

# =========================================================================
# 5. MARKETING
# =========================================================================

add("seo-specialist", "marketing", "seo-specialist", "SEO Specialist",
    "SEO skills for improving the organic visibility of the platform and any customer-facing pages, with attention to local/regional SEO where relevant. Trigger this skill for SEO optimization, keyword research, or technical SEO audits.",
    "The SEO Specialist optimizes the organic visibility of the platform and any customer-facing pages, with a strategy adapted to the target market's real search behavior (mobile, local searches, languages).",
    ["Technical SEO audit of a site or storefront",
     "Keyword research relevant to the target market",
     "On-page optimization (tags, structure, content)",
     "Local SEO strategy (city, neighborhood, service area)"],
    ["Technical SEO: meta tags, structured data (schema.org), sitemap, mobile load speed",
     "Keyword research in the languages actually used by your target audience",
     "Local SEO optimization for location-based pages (service areas, cities covered)",
     "Content optimized for real search intent (informational vs. transactional)",
     "Tracking rankings and organic traffic over time"],
    ["Focusing only on generic keywords with no local dimension",
     "Neglecting mobile speed, which directly affects ranking and experience on slow networks",
     "Duplicate content across multiple storefronts (SEO penalty)"],
    ["Google Search Console",
     "Sitemap and metadata tooling built into your framework",
     "Keyword research tools (Ubersuggest, Google Keyword Planner)"],
    ["Technical SEO audit",
     "Prioritized keyword list",
     "On-page and content recommendations"],
    ["'Optimize the storefronts for local search in our target cities'",
     "'Run a technical SEO audit to find what's holding back our rankings'"])

add("content-marketing", "marketing", "content-marketing", "Content Marketing / Copywriter",
    "Content marketing and copywriting skills for creating content that converts (product pages, blog posts, sales copy) with a tone fit for the target market. Trigger this skill for marketing content, blog writing, or persuasive copywriting.",
    "The Content Marketer/Copywriter creates clear, persuasive content that builds trust and converts, with a tone adapted to the culture and expectations of the target audience.",
    ["Writing marketing content (product page, landing page, blog post)",
     "Persuasive copywriting to convert a visitor into a paying customer",
     "Defining an editorial line or content calendar",
     "Adapting brand tone by audience (B2B vs. B2C customers)"],
    ["Content centered on concrete reader benefits, not technical features",
     "A trustworthy, approachable tone anchored in local cultural norms",
     "Clear structure with an explicit call to action in every piece",
     "Social proof and concrete case studies to build trust",
     "Consistent tone across every channel (site, social, transactional messages)"],
    ["Copying a generic marketing tone from another market with no local grounding",
     "Content that's too technical/feature-oriented instead of benefit-oriented",
     "No clear call to action at the end of a piece"],
    ["Editorial planning tools (Notion)",
     "A blog/CMS built into your stack (MDX, headless CMS, etc.)"],
    ["Publish-ready content",
     "Editorial calendar",
     "Brand tone guide"],
    ["'Write the homepage copy to convince business accounts to sign up'",
     "'Write a blog post explaining the benefits of our service to customers'"])

add("paid-ads-sea", "marketing", "paid-ads-sea", "SEA / Paid Ads Specialist",
    "Paid advertising skills (Google Ads, Meta Ads) for efficiently generating leads and customers on a controlled budget. Trigger this skill for paid ad campaigns, ad targeting, or acquisition cost optimization.",
    "The SEA/Paid Ads Specialist designs and optimizes paid campaigns to generate qualified leads (B2B accounts, customers) at the best possible acquisition cost.",
    ["Designing a Google Ads or Meta Ads campaign",
     "Defining ad targeting (geography, interests)",
     "Optimizing the acquisition cost (CAC) of an existing campaign",
     "A/B testing creatives or ad copy"],
    ["Precise geographic targeting aligned with areas you can actually serve",
     "Ad copy centered on one clear benefit (not information overload)",
     "Rigorous tracking of acquisition cost and ROI per channel",
     "Systematic A/B testing of creatives/copy before scaling budget",
     "Landing pages consistent with the ad's promise (no experience break)"],
    ["Targeting areas you can't actually serve (wasted budget)",
     "Scaling budget before validating a message that actually converts",
     "No tracking of real acquisition cost per channel and campaign"],
    ["Google Ads / Meta Ads Manager",
     "Conversion tracking pixel on your site",
     "Analytics tooling to measure ROI per channel"],
    ["Ad campaign plan",
     "Performance and acquisition cost report",
     "Budget optimization recommendations"],
    ["'Design a Meta Ads campaign to recruit business accounts in our target city'",
     "'Our Google Ads acquisition cost is too high, help me optimize it'"])

add("social-media-manager", "marketing", "social-media-manager", "Social Media / Community Manager",
    "Social media and community management skills for building awareness and trust with customers and partners on the platforms popular in your market. Trigger this skill for content calendars, social media strategy, or online community management.",
    "The Social Media/Community Manager builds a trustworthy presence on the platforms popular with the target audience, engages the customer community, and manages online reputation.",
    ["Defining a social media strategy",
     "Building a content calendar",
     "Community management (comments, messages, reviews)",
     "Handling an online reputation issue (negative review, public incident)"],
    ["Platform choice based on real local usage (WhatsApp, Facebook, TikTok, Instagram, etc.)",
     "A varied content calendar: educational, social proof, behind-the-scenes, offers",
     "Fast, human responses to community comments and messages",
     "Proactive reputation management, especially around service incidents",
     "Measuring real engagement, not just follower count"],
    ["Focusing on platforms your actual audience doesn't use much",
     "Publishing with no consistent cadence",
     "Ignoring or slowly responding to negative reviews (erodes trust)"],
    ["Meta Business Suite",
     "WhatsApp Business",
     "Content scheduling tools"],
    ["Content calendar",
     "Community management guide",
     "Online reputation management plan"],
    ["'Help me plan this month's social content to promote the platform'",
     "'How should I respond to customers unhappy about a service delay on Facebook?'"])

# =========================================================================
# 6. DATA
# =========================================================================

add("data-analyst", "data", "data-analyst", "Data Analyst",
    "Skills of a Data Analyst for exploiting existing data (orders, transactions, users) and producing actionable analysis for business decisions. Trigger this skill for analyzing data that's already available, building a tracking dashboard, or answering a business question with numbers — distinct from the Data Engineer, who builds the pipelines.",
    "The Data Analyst answers concrete business questions (conversion rate by segment, team/agent performance, customer retention) using data already available in the operational database.",
    ["Analyzing failure/success rates by segment or zone",
     "Analyzing team, agent or partner performance",
     "Building a business tracking dashboard",
     "Answering a specific business question with numbers"],
    ["Clearly defining the business question before starting the analysis",
     "Checking data quality and freshness before drawing conclusions",
     "Simple, readable visualizations suited to a business (not just technical) audience",
     "Clearly distinguishing correlation from causation in conclusions",
     "Actionable recommendations, not just raw numbers"],
    ["Presenting numbers with no context or actionable recommendation",
     "Confusing correlation with causation (e.g. 'evening orders fail more' without digging into why)",
     "Building dashboards with too many non-actionable metrics"],
    ["SQL on your operational database for extraction",
     "Metabase or a lightweight BI tool for dashboards",
     "Pandas/Python for more complex ad hoc analysis"],
    ["Analysis report with recommendations",
     "Tracking dashboard",
     "Documented, reusable SQL queries"],
    ["'What's the failure rate by city over the last 3 months?'",
     "'Build a performance dashboard for the sales team'"])

add("data-scientist", "data", "data-scientist", "Data Scientist",
    "Skills of a Data Scientist for advanced statistical analysis and exploratory modeling, complementing the ML/AI Engineer, who focuses on productionizing models. Trigger this skill for deep statistical analysis, customer segmentation, or exploring patterns in data.",
    "The Data Scientist digs deep into the data to surface statistically grounded patterns (customer segmentation, failure factors) that inform product and business strategy.",
    ["Statistical segmentation of customers or accounts",
     "Exploratory analysis to identify factors behind churn or failed transactions",
     "Statistical tests to validate or invalidate a business hypothesis",
     "Exploring new data use cases before investing in ML engineering"],
    ["Rigorous exploratory analysis before any conclusion (distribution, outliers)",
     "Statistical tests appropriate to the data (not chosen at random)",
     "Segmentation based on variables the business can actually act on",
     "Communicating uncertainty and statistical limits, not just clean-sounding conclusions",
     "Close collaboration with the Data Analyst and ML Engineer for the rest of the cycle"],
    ["Drawing causal conclusions from simple observed correlations",
     "Sophisticated segmentation that's not actionable for business teams",
     "Ignoring sample size or statistical significance of results"],
    ["Python (pandas, scipy, scikit-learn)",
     "Jupyter notebooks for exploration",
     "Your operational database as the data source"],
    ["Statistical analysis report",
     "Documented customer segments",
     "Recommendations grounded in the results"],
    ["'Identify the factors that best explain failed transactions'",
     "'Segment our customers by purchasing behavior'"])

add("bi-analyst", "data", "bi-analyst", "BI Analyst",
    "Business Intelligence skills for building reliable dashboards distributed widely across the company, with clear governance over metrics. Trigger this skill for recurring BI dashboards, official KPI definitions, or periodic reporting to different teams.",
    "The BI Analyst builds and maintains the company's reference dashboards, with stable metric definitions shared by every team (leadership, operations, marketing).",
    ["Designing a recurring BI dashboard (weekly, monthly)",
     "Officially defining the company's KPIs",
     "Periodic reporting for leadership or operational teams",
     "Reconciling inconsistent metrics across teams"],
    ["A single, official metrics dictionary shared by every team",
     "Dashboards designed for their audience (leadership vs. operational) at the right level of detail",
     "Automated reporting to avoid error-prone manual updates",
     "Historical data retention to allow comparisons over time",
     "Regular review of which KPIs are still worth tracking (avoid stale dashboards)"],
    ["The same metric computed differently by different teams (numbers stop matching)",
     "Dashboards overloaded with information that isn't actionable for the intended audience",
     "Repetitive manual reporting with no automation, prone to error and wasted time"],
    ["Metabase or an equivalent lightweight BI tool",
     "Your database / materialized views as the data source"],
    ["Official metrics dictionary",
     "Automated BI dashboards",
     "Periodic report for leadership"],
    ["'Build the monthly growth dashboard for leadership'",
     "'Different teams calculate retention differently, help me standardize the definition'"])

# =========================================================================
# File generation
# =========================================================================

CATEGORY_LABELS = {
    "dev": "Engineering",
    "security": "Security",
    "design-product": "Design & Product",
    "business-strategy": "Business & Strategy",
    "marketing": "Marketing",
    "data": "Data",
}


def main():
    index_by_cat = {}
    for p in PROFILES:
        folder = os.path.join(SKILLS_DIR, p["category"], p["key"])
        os.makedirs(folder, exist_ok=True)
        content = render_skill(p)
        with open(os.path.join(folder, "SKILL.md"), "w", encoding="utf-8") as f:
            f.write(content)
        index_by_cat.setdefault(p["category"], []).append(p)
        print(f"Created: {p['category']}/{p['key']}/SKILL.md")
    print(f"\nTotal: {len(PROFILES)} skills generated in {SKILLS_DIR}")
    return index_by_cat


if __name__ == "__main__":
    main()
